export const GO_TO_VERIFY = 'GO_TO_VERIFY';
export const LOAD_UI_SCHEMA = 'LOAD_UI_SCHEMA';
export const SUBMIT_PAYMENT_DETAILS = 'SUBMIT_PAYMENT_DETAILS';
export const LOAD_REST_UI_SCHEMA = 'LOAD_REST_UI_SCHEMA';
export const LOAD_ACCOUNTS_LIST = 'LOAD_ACCOUNTS_LIST';
// export const FETCH_ACCOUNTS_LIST = 'FETCH_ACCOUNTS_LIST';
